CREATE TABLE app_users (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 username VARCHAR(40) NOT NULL UNIQUE,
 password_hash VARCHAR(100) NOT NULL
);
ALTER TABLE tasks ADD COLUMN due_date DATE;
ALTER TABLE tasks ADD COLUMN owner_id BIGINT REFERENCES app_users(id);
CREATE INDEX tasks_owner_created ON tasks(owner_id, created_at);
-- Pre-upgrade tasks remain unassigned until the database owner explicitly assigns them.
